gText_Birch_Welcome::
	.string "Hello! Welcome to my entry for\n"
	.string "the Team Aqua Hacking Competition!\p"
	.string "I am Professor Spruce, from the\n"
	.string "region of Ecodia.\p"
	.string "This region is experiencing a\n"
	.string "great number of climate disasters,\l"
	.string "as you will soon discover.\p"
	.string "But first, tell me,\p"
	.string "$"

gText_Birch_Pokemon::
	.string "This is what we call a “POKéMON.”\p"
	.string "\n"
	.string "$"

gText_Birch_MainSpeech::
	.string "This world is widely inhabited by\n"
	.string "creatures known as POKéMON.\p"
	.string "We humans live alongside POKéMON,\n"
	.string "at times as friendly playmates, and\l"
	.string "at times as cooperative workmates.\p"
	.string "And sometimes, we band together\n"
	.string "and battle others like us.\p"
	.string "But despite our closeness, we don't\n"
	.string "know everything about POKéMON.\p"
	.string "In fact, there are many, many\n"
	.string "secrets surrounding POKéMON.\p"
	.string "To unravel POKéMON mysteries,\n"
	.string "I've been undertaking research.\l"
	.string "That's what I do.\p"
	.string "$"

gText_Birch_AndYouAre::
	.string "Who are you?$"

gText_Birch_BoyOrGirl::
	.string "Are you a boy?\n"
	.string "Or are you a girl?$"

gText_Birch_WhatsYourName::
	.string "What's your name?$"

gText_Birch_SoItsPlayer::
	.string "{PLAYER}{KUN}? Is that right?$"

gText_Birch_YourePlayer::
	.string "Nice to meet you, {PLAYER}{KUN}!\p"
	.string "I hope you enjoy a brief introduction\n"
	.string "to Ecodia!\p"
	.string "$"

gText_Birch_AreYouReady::
	.string "Shortly, you will find yourself in\n"
	.string "Seaspray Town, developed just for\l"
	.string "this competition.\p"
	.string "Please enjoy, and let me know\n"
	.string "if you have any feedback!\p"
	.string "Good luck!\p"
	.string "$"
