# 1 "data/maps/OldaleTown_House2/scripts.pory"
OldaleTown_House2_MapScripts::
# 2 "data/maps/OldaleTown_House2/scripts.pory"
	.byte 0
# 3 "data/maps/OldaleTown_House2/scripts.pory"

# 4 "data/maps/OldaleTown_House2/scripts.pory"
OldaleTown_House2_EventScript_Woman::
# 5 "data/maps/OldaleTown_House2/scripts.pory"
	msgbox OldaleTown_House2_Text_PokemonLevelUp, MSGBOX_NPC
# 6 "data/maps/OldaleTown_House2/scripts.pory"
	end
# 7 "data/maps/OldaleTown_House2/scripts.pory"

# 8 "data/maps/OldaleTown_House2/scripts.pory"
OldaleTown_House2_EventScript_Man::
# 9 "data/maps/OldaleTown_House2/scripts.pory"
	msgbox OldaleTown_House2_Text_YoullGoFurtherWithStrongPokemon, MSGBOX_NPC
# 10 "data/maps/OldaleTown_House2/scripts.pory"
	end
# 11 "data/maps/OldaleTown_House2/scripts.pory"

# 12 "data/maps/OldaleTown_House2/scripts.pory"
OldaleTown_House2_Text_PokemonLevelUp:
# 13 "data/maps/OldaleTown_House2/scripts.pory"
	.string "When POKéMON battle, they eventually\n"
# 14 "data/maps/OldaleTown_House2/scripts.pory"
	.string "level up and become stronger.$"
# 15 "data/maps/OldaleTown_House2/scripts.pory"

# 16 "data/maps/OldaleTown_House2/scripts.pory"
OldaleTown_House2_Text_YoullGoFurtherWithStrongPokemon:
# 17 "data/maps/OldaleTown_House2/scripts.pory"
	.string "If the POKéMON with you become\n"
# 18 "data/maps/OldaleTown_House2/scripts.pory"
	.string "stronger, you'll be able to go farther\l"
# 19 "data/maps/OldaleTown_House2/scripts.pory"
	.string "away from here.$"
